// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmosacademyexercisesimple/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_50e7c1ea3abe958e, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_50e7c1ea3abe958e, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetWorldParams2Request struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetWorldParams2Request) Reset()         { *m = QueryGetWorldParams2Request{} }
func (m *QueryGetWorldParams2Request) String() string { return proto.CompactTextString(m) }
func (*QueryGetWorldParams2Request) ProtoMessage()    {}
func (*QueryGetWorldParams2Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_50e7c1ea3abe958e, []int{2}
}
func (m *QueryGetWorldParams2Request) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetWorldParams2Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetWorldParams2Request.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetWorldParams2Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetWorldParams2Request.Merge(m, src)
}
func (m *QueryGetWorldParams2Request) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetWorldParams2Request) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetWorldParams2Request.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetWorldParams2Request proto.InternalMessageInfo

func (m *QueryGetWorldParams2Request) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetWorldParams2Response struct {
	WorldParams2 WorldParams2 `protobuf:"bytes,1,opt,name=WorldParams2,proto3" json:"WorldParams2"`
}

func (m *QueryGetWorldParams2Response) Reset()         { *m = QueryGetWorldParams2Response{} }
func (m *QueryGetWorldParams2Response) String() string { return proto.CompactTextString(m) }
func (*QueryGetWorldParams2Response) ProtoMessage()    {}
func (*QueryGetWorldParams2Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_50e7c1ea3abe958e, []int{3}
}
func (m *QueryGetWorldParams2Response) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetWorldParams2Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetWorldParams2Response.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetWorldParams2Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetWorldParams2Response.Merge(m, src)
}
func (m *QueryGetWorldParams2Response) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetWorldParams2Response) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetWorldParams2Response.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetWorldParams2Response proto.InternalMessageInfo

func (m *QueryGetWorldParams2Response) GetWorldParams2() WorldParams2 {
	if m != nil {
		return m.WorldParams2
	}
	return WorldParams2{}
}

type QueryAllWorldParams2Request struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllWorldParams2Request) Reset()         { *m = QueryAllWorldParams2Request{} }
func (m *QueryAllWorldParams2Request) String() string { return proto.CompactTextString(m) }
func (*QueryAllWorldParams2Request) ProtoMessage()    {}
func (*QueryAllWorldParams2Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_50e7c1ea3abe958e, []int{4}
}
func (m *QueryAllWorldParams2Request) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllWorldParams2Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllWorldParams2Request.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllWorldParams2Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllWorldParams2Request.Merge(m, src)
}
func (m *QueryAllWorldParams2Request) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllWorldParams2Request) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllWorldParams2Request.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllWorldParams2Request proto.InternalMessageInfo

func (m *QueryAllWorldParams2Request) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllWorldParams2Response struct {
	WorldParams2 []WorldParams2      `protobuf:"bytes,1,rep,name=WorldParams2,proto3" json:"WorldParams2"`
	Pagination   *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllWorldParams2Response) Reset()         { *m = QueryAllWorldParams2Response{} }
func (m *QueryAllWorldParams2Response) String() string { return proto.CompactTextString(m) }
func (*QueryAllWorldParams2Response) ProtoMessage()    {}
func (*QueryAllWorldParams2Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_50e7c1ea3abe958e, []int{5}
}
func (m *QueryAllWorldParams2Response) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllWorldParams2Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllWorldParams2Response.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllWorldParams2Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllWorldParams2Response.Merge(m, src)
}
func (m *QueryAllWorldParams2Response) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllWorldParams2Response) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllWorldParams2Response.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllWorldParams2Response proto.InternalMessageInfo

func (m *QueryAllWorldParams2Response) GetWorldParams2() []WorldParams2 {
	if m != nil {
		return m.WorldParams2
	}
	return nil
}

func (m *QueryAllWorldParams2Response) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "b9lab.cosmosacademyexercisesimple.cosmosacademyexercisesimple.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "b9lab.cosmosacademyexercisesimple.cosmosacademyexercisesimple.QueryParamsResponse")
	proto.RegisterType((*QueryGetWorldParams2Request)(nil), "b9lab.cosmosacademyexercisesimple.cosmosacademyexercisesimple.QueryGetWorldParams2Request")
	proto.RegisterType((*QueryGetWorldParams2Response)(nil), "b9lab.cosmosacademyexercisesimple.cosmosacademyexercisesimple.QueryGetWorldParams2Response")
	proto.RegisterType((*QueryAllWorldParams2Request)(nil), "b9lab.cosmosacademyexercisesimple.cosmosacademyexercisesimple.QueryAllWorldParams2Request")
	proto.RegisterType((*QueryAllWorldParams2Response)(nil), "b9lab.cosmosacademyexercisesimple.cosmosacademyexercisesimple.QueryAllWorldParams2Response")
}

func init() {
	proto.RegisterFile("cosmosacademyexercisesimple/query.proto", fileDescriptor_50e7c1ea3abe958e)
}

var fileDescriptor_50e7c1ea3abe958e = []byte{
	// 529 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0x4f, 0x6b, 0xd4, 0x40,
	0x14, 0xdf, 0xc4, 0xba, 0x87, 0x51, 0x14, 0xc6, 0x1e, 0x64, 0x2d, 0x51, 0x72, 0xb0, 0x45, 0xd8,
	0x8c, 0x5d, 0x4f, 0x1e, 0x3c, 0xb4, 0xa0, 0x15, 0x8b, 0xb0, 0x4d, 0x0f, 0x4a, 0x3d, 0x94, 0xc9,
	0x66, 0x88, 0x03, 0x49, 0x26, 0xcd, 0x24, 0xda, 0x55, 0x3c, 0xe8, 0x27, 0x10, 0xc4, 0xb3, 0xf8,
	0x6d, 0x7a, 0xac, 0x78, 0xf1, 0x54, 0x64, 0xd7, 0x0f, 0x22, 0x99, 0x79, 0x8b, 0x09, 0xcd, 0x66,
	0x85, 0x8d, 0xde, 0x96, 0x99, 0xf7, 0x7e, 0xff, 0xe6, 0xbd, 0x0d, 0x5a, 0x1f, 0x09, 0x19, 0x09,
	0x49, 0x47, 0xd4, 0x67, 0xd1, 0x98, 0x1d, 0xb3, 0x74, 0xc4, 0x25, 0x93, 0x3c, 0x4a, 0x42, 0x46,
	0x8e, 0x72, 0x96, 0x8e, 0x9d, 0x24, 0x15, 0x99, 0xc0, 0x0f, 0xbc, 0xfb, 0x21, 0xf5, 0x9c, 0x86,
	0xf2, 0xa6, 0xbb, 0xde, 0x6a, 0x20, 0x02, 0xa1, 0x90, 0x48, 0xf1, 0x4b, 0x83, 0xf6, 0xd6, 0x02,
	0x21, 0x82, 0x90, 0x11, 0x9a, 0x70, 0x42, 0xe3, 0x58, 0x64, 0x34, 0xe3, 0x22, 0x96, 0x70, 0x7b,
	0x47, 0x03, 0x12, 0x8f, 0x4a, 0xd0, 0x42, 0x5e, 0x6d, 0x7a, 0x2c, 0xa3, 0x9b, 0x24, 0xa1, 0x01,
	0x8f, 0x55, 0x31, 0xd4, 0x6e, 0x34, 0xf9, 0x48, 0x68, 0x4a, 0xa3, 0x19, 0xea, 0xdd, 0xa6, 0xca,
	0xd7, 0x22, 0x0d, 0xfd, 0x43, 0x5d, 0x7f, 0x38, 0xd0, 0x1d, 0xf6, 0x2a, 0xc2, 0x7b, 0x05, 0xfb,
	0x50, 0x1d, 0xbb, 0xec, 0x28, 0x67, 0x32, 0xb3, 0xdf, 0xa0, 0x6b, 0x95, 0x53, 0x99, 0x88, 0x58,
	0x32, 0x3c, 0x42, 0x5d, 0xdd, 0x7e, 0xdd, 0xb8, 0x65, 0x6c, 0x5c, 0x1a, 0x3c, 0x74, 0x96, 0x0a,
	0xce, 0xd1, 0xf0, 0xdb, 0x2b, 0x27, 0x67, 0x37, 0x3b, 0x2e, 0x40, 0xdb, 0x7d, 0x74, 0x43, 0x71,
	0xef, 0xb0, 0xec, 0x59, 0xa1, 0x58, 0x17, 0x0d, 0x40, 0x1a, 0xbe, 0x82, 0x4c, 0xee, 0x2b, 0xfe,
	0x15, 0xd7, 0xe4, 0xbe, 0xfd, 0xd9, 0x40, 0x6b, 0xf5, 0xf5, 0x20, 0x3a, 0x47, 0x97, 0xcb, 0xe7,
	0x20, 0x7d, 0x77, 0x49, 0xe9, 0x65, 0x48, 0x30, 0x50, 0xa1, 0xb1, 0x19, 0xd8, 0xd8, 0x0a, 0xc3,
	0x3a, 0x1b, 0x8f, 0x10, 0xfa, 0xf3, 0xce, 0xa0, 0xe9, 0x36, 0x30, 0x3a, 0xc5, 0x50, 0x38, 0x7a,
	0x40, 0x61, 0x28, 0x9c, 0x21, 0x0d, 0x18, 0xf4, 0xba, 0xa5, 0x4e, 0xfb, 0x6c, 0x66, 0xff, 0x1c,
	0xcf, 0x5c, 0xfb, 0x17, 0xfe, 0x83, 0x7d, 0xbc, 0x53, 0xf1, 0x67, 0x2a, 0x7f, 0xeb, 0x0b, 0xfd,
	0x69, 0xcd, 0x65, 0x83, 0x83, 0x6f, 0x5d, 0x74, 0x51, 0x19, 0xc4, 0xef, 0x4d, 0xd4, 0xd5, 0xf0,
	0x78, 0x6f, 0x49, 0xf9, 0xe7, 0x47, 0xbe, 0xe7, 0xb6, 0x09, 0xa9, 0x7d, 0xd8, 0xc3, 0x0f, 0xdf,
	0x7f, 0x7d, 0x32, 0x9f, 0xe0, 0xc7, 0x44, 0x61, 0x13, 0xdd, 0xdf, 0x07, 0x80, 0xfe, 0x0c, 0xa1,
	0x0f, 0x0b, 0xba, 0x78, 0xcd, 0xf1, 0x57, 0xb3, 0xfa, 0x9c, 0xf8, 0xa0, 0x0d, 0xd9, 0xf5, 0xab,
	0xd6, 0x7b, 0xf1, 0x4f, 0xb0, 0x21, 0x9b, 0xe7, 0x2a, 0x1b, 0x17, 0x0f, 0x2b, 0xd9, 0xd4, 0x9b,
	0x5f, 0xf8, 0xaf, 0x06, 0xe0, 0xe4, 0x2d, 0xf7, 0xdf, 0xe1, 0x2f, 0x26, 0xba, 0x5a, 0xa6, 0xdc,
	0x0a, 0xc3, 0x76, 0x62, 0xaa, 0x5f, 0xe5, 0x76, 0x62, 0x9a, 0xb3, 0xbe, 0xf6, 0xbe, 0x8a, 0xe9,
	0x29, 0xde, 0x6d, 0x31, 0xa6, 0xed, 0xe8, 0x64, 0x62, 0x19, 0xa7, 0x13, 0xcb, 0xf8, 0x39, 0xb1,
	0x8c, 0x8f, 0x53, 0xab, 0x73, 0x3a, 0xb5, 0x3a, 0x3f, 0xa6, 0x56, 0xe7, 0x60, 0x3f, 0xe0, 0xd9,
	0xcb, 0xbc, 0xf0, 0x12, 0xfd, 0xdd, 0xcc, 0x1e, 0x37, 0xb2, 0x66, 0xe3, 0x84, 0x49, 0xaf, 0xab,
	0x3e, 0x35, 0xf7, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x2d, 0xdc, 0x24, 0x9a, 0x90, 0x07, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a worldParams2 by id.
	WorldParams2(ctx context.Context, in *QueryGetWorldParams2Request, opts ...grpc.CallOption) (*QueryGetWorldParams2Response, error)
	// Queries a list of worldParams2 items.
	WorldParams2All(ctx context.Context, in *QueryAllWorldParams2Request, opts ...grpc.CallOption) (*QueryAllWorldParams2Response, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/b9lab.cosmosacademyexercisesimple.cosmosacademyexercisesimple.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) WorldParams2(ctx context.Context, in *QueryGetWorldParams2Request, opts ...grpc.CallOption) (*QueryGetWorldParams2Response, error) {
	out := new(QueryGetWorldParams2Response)
	err := c.cc.Invoke(ctx, "/b9lab.cosmosacademyexercisesimple.cosmosacademyexercisesimple.Query/WorldParams2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) WorldParams2All(ctx context.Context, in *QueryAllWorldParams2Request, opts ...grpc.CallOption) (*QueryAllWorldParams2Response, error) {
	out := new(QueryAllWorldParams2Response)
	err := c.cc.Invoke(ctx, "/b9lab.cosmosacademyexercisesimple.cosmosacademyexercisesimple.Query/WorldParams2All", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a worldParams2 by id.
	WorldParams2(context.Context, *QueryGetWorldParams2Request) (*QueryGetWorldParams2Response, error)
	// Queries a list of worldParams2 items.
	WorldParams2All(context.Context, *QueryAllWorldParams2Request) (*QueryAllWorldParams2Response, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) WorldParams2(ctx context.Context, req *QueryGetWorldParams2Request) (*QueryGetWorldParams2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WorldParams2 not implemented")
}
func (*UnimplementedQueryServer) WorldParams2All(ctx context.Context, req *QueryAllWorldParams2Request) (*QueryAllWorldParams2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WorldParams2All not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/b9lab.cosmosacademyexercisesimple.cosmosacademyexercisesimple.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_WorldParams2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetWorldParams2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).WorldParams2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/b9lab.cosmosacademyexercisesimple.cosmosacademyexercisesimple.Query/WorldParams2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).WorldParams2(ctx, req.(*QueryGetWorldParams2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_WorldParams2All_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllWorldParams2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).WorldParams2All(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/b9lab.cosmosacademyexercisesimple.cosmosacademyexercisesimple.Query/WorldParams2All",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).WorldParams2All(ctx, req.(*QueryAllWorldParams2Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "b9lab.cosmosacademyexercisesimple.cosmosacademyexercisesimple.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "WorldParams2",
			Handler:    _Query_WorldParams2_Handler,
		},
		{
			MethodName: "WorldParams2All",
			Handler:    _Query_WorldParams2All_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmosacademyexercisesimple/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetWorldParams2Request) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetWorldParams2Request) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetWorldParams2Request) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetWorldParams2Response) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetWorldParams2Response) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetWorldParams2Response) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.WorldParams2.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllWorldParams2Request) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllWorldParams2Request) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllWorldParams2Request) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllWorldParams2Response) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllWorldParams2Response) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllWorldParams2Response) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.WorldParams2) > 0 {
		for iNdEx := len(m.WorldParams2) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.WorldParams2[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetWorldParams2Request) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetWorldParams2Response) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.WorldParams2.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllWorldParams2Request) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllWorldParams2Response) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.WorldParams2) > 0 {
		for _, e := range m.WorldParams2 {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetWorldParams2Request) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetWorldParams2Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetWorldParams2Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetWorldParams2Response) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetWorldParams2Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetWorldParams2Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorldParams2", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.WorldParams2.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllWorldParams2Request) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllWorldParams2Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllWorldParams2Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllWorldParams2Response) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllWorldParams2Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllWorldParams2Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorldParams2", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WorldParams2 = append(m.WorldParams2, WorldParams2{})
			if err := m.WorldParams2[len(m.WorldParams2)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
